---
title: "Papers"
---

# MA at University of Groningen

Affective Polarization and Its Measurement in the United States\
Spring 2025

Urban-Rural News Media Attitudes in the United States\
Spring 2025

Climate Attitudes and State Climate Policies in the United States\
Spring 2025

Who Votes for Trump? — A Research Outline\
Fall 2024

Geographic Variation of Populist Attitudes in the United States\
Fall 2024

Populist Attitudes in the United States\
Fall 2024

Performing Populism: Approaches to Populism as a Political Style\
Fall 2024

Quantifying and Qualifying Contemporary Populist Support\
Fall 2024

# BA at UC San Diego

Here is a list of some of the papers I wrote:

US Foreign Policy: Human Security as National Security\
Spring 2023

To Legislate Hate: The Nuremberg Laws of 1935\
Winter 2023

The Ethics of Vaccine Mandates for COVID-19\
Spring 2022

European Social Model: Healthcare\
Spring 2022

The Metamorphosis of Warfare During the US Civil War\
Fall 2022

Tortured Logic: Why the US Should Never Use Enhanced Interrogation\
Fall 2021

Duplicity and Discrimination in Mississippi’s First Black Code\
Fall 2020

Post-Plague Labor Laws Suppress the English Poor\
Spring 2020
